### ISSUE TITLE
What is the approximate scarebleu score of the de_en dataset in the example？

### ISSUE THREAD

**Issue by y94688** [DeepLearnXMU/Robust-knn-mt#2]
Hello, I would like to ask that the score of the de_en data set is very low, and the score I run is 3.63, is this normal？

**Comment by lighter47** [comment]
This is not normal, but I don't know what your experimental setup is.
You can debug in the following steps:
1. Run base NMT to ensure that the performance of the pretrained model is normal.
2. Run vanilla kNN-MT to verify that the datastore is useful.
3. If both models perform well, you can try to adjust the hyperparameters of robust kNN-MT. We recommend setting beta to 0 first to ensure that the trained module is useful.

**Comment by y94688** [comment]
I have found this problem due to insufficient memory of the graphics card, thank you for your suggestion!! Great implementation results
